version: "3.4"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  node:
    image: node:14
    networks:
      - app
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app:delegated

  cypress:
    image: cypress/included:7.7.0
    networks:
      - app
    environment:
      - CYPRESS_VIDEO=false
      - CYPRESS_baseUrl=http://host.docker.internal
      #- DISPLAY=host.docker.internal:0
    volumes:
      - .:/e2e
    working_dir: /e2e
    entrypoint: cypress
