version: "3.4"

networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  nginx:
    image: nginx:latest
    networks:
      - app
      - frontend
    depends_on:
      - node
    ports:
      - '80'
    volumes:
      - ${PWD}/.docker/vhost.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/app:delegated
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_DOMAIN}`)"
      #      HTTPS config - uncomment to enable redirect from :80 to :443
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  node:
    image: node:14
    command: npm start
    networks:
      - app
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app:delegated
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://node:3000/tags" ]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 60s

  mariadb:
    # Database with pre-load fixtures for testing for the API.
    image: itkdev/os2display-api-mariadb:alpha
    networks:
      - app
    environment:
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: password

  cypress:
    image: cypress/included:9.1.1
    networks:
      - app
      - frontend
    depends_on:
      - nginx
    environment:
      - CYPRESS_VIDEO=false
      - CYPRESS_baseUrl=http://nginx
    volumes:
      - .:/e2e
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /e2e
    entrypoint: cypress
