version: "3.7"

services:
  api:
    image: itkdev/os2display-api-service:alpha
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_MAX_EXECUTION_TIME: 30
      PHP_MEMORY_LIMIT: 128M
      PHP_UPLOAD_MAX_FILESIZE: 8M
      APP_ENV: prod
      APP_TRUSTED_PROXIES: 127.0.0.1,REMOTE_ADDR
      APP_SECRET: MySuperSecret
      APP_CORS_ALLOW_ORIGIN: '*'
      APP_DATABASE_URL: mysql://db:db@host.docker.internal:3306/db?serverVersion=mariadb-10.4.21
      APP_DEFAULT_DATE_FORMAT: Y-m-d\TH:i:s.v\Z

  nginx-api:
    image: itkdev/os2display-api-service-nginx:alpha
    depends_on:
      - api
    environment:
      PHP_FPM_SERVER: api
      NGINX_FPM_UPLOAD_MAX: 8M

  node:
    image: node:14
    command: npm start
    working_dir: /app
    depends_on:
      - nginx-api
      - api
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://node:3000/tags"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 60s
    volumes:
      - .:/app:delegated

  cypress:
    image: cypress/included:7.7.0
    depends_on:
      node:
        condition: service_healthy
    working_dir: /e2e
    entrypoint: cypress
    environment:
      - CYPRESS_VIDEO=false
      - CYPRESS_baseUrl=http://node:3000
      #- DISPLAY=host.docker.internal:0
    volumes:
      - .:/e2e
