version: "3.4"

services:
  node:
    image: node:14
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app:delegated

  cypress:
    image: cypress/included:7.7.0
    network_mode: "host"
    environment:
      - CYPRESS_VIDEO=false
      - CYPRESS_baseUrl=http://127.0.0.1
      #- DISPLAY=host.docker.internal:0
    volumes:
      - .:/e2e
    working_dir: /e2e
    entrypoint: cypress
